/*
 * generated by Xtext 2.9.1
 */
package org.xtext.ceu.validation

import org.eclipse.xtext.validation.Check
import org.xtext.ceu.ceu.Dcl_var
import org.xtext.ceu.ceu.Dcl_var_plain_set
import org.xtext.ceu.ceu.CeuPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class CeuValidator extends AbstractCeuValidator {
	
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					CeuPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	@Check
	def checkIfVarsAreInitialized(Dcl_var d) {
		val referenceBlockI = d.type.type_cls_adt.eContents.get(0).eContents
//		var notInitializedVars = 0;
		for (vars : referenceBlockI) {
//			notInitializedVars++
			if (vars instanceof Dcl_var) {
				for (Varsets : vars.eContents) {
					if (Varsets instanceof Dcl_var_plain_set && d.dcl_var_org == null) {
						warning("Variables of Organism < > are not initialized", CeuPackage.Literals.DCL_VAR__DCL_VAR_ORG)
					}
				}
			}
		}
		
	}
	
}
