/*
 * generated by Xtext 2.9.1
 */
package org.xtext.ceu.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class CeuProposalProvider extends AbstractCeuProposalProvider {
}
