/*
 * generated by Xtext 2.9.1
 */
package org.xtext.ceu


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CeuRuntimeModule extends AbstractCeuRuntimeModule {
}
